config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resource :editor_settings, :only => ['show', 'update', 'edit']
  end

  resources :content_images, :only => [:create]
  resources :content_files, :only => [:create]
end

app/models/content_file.rb
class ContentFile < Asset
  has_attached_file :attachment,
    :url => "/assets/content_files/:id/:basename.:extension",
    :path => ":rails_root/public/assets/content_files/:id/:basename.:extension"
end

app/models/content_image.rb
class ContentImage < Image
  has_attached_file :attachment, 
    :styles => {:mini => '48x48#', :large => '600x600>'},
    :default_style => :large,
    :url => "/assets/content_images/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/content_images/:id/:style/:basename.:extension"
end

app/controllers/admin/editor_settings_controller.rb
class Admin::EditorSettingsController < Admin::BaseController
  def update
    @config = Spree::Editor::Config.instance
    @config.update_attributes(params[@config.class.name.underscore])
    Rails.cache.delete("configuration_#{@config.class.name}".to_sym)
    redirect_to admin_editor_settings_path
  end
end

app/controllers/content_files_controller.rb
class ContentFilesController < Spree::BaseController

  def create
    @content_file = ContentFile.new(params[:content_file])
    @content_file.save!

    render :text => "#{@content_file.attachment.url},#{@content_file.attachment_file_name}"
  end

end

app/controllers/content_images_controller.rb
class ContentImagesController < Spree::BaseController

  def create
    @content_image = ContentImage.new(params[:content_image])
    @content_image.save!

    render :text => @content_image.attachment.url
  end

end

app/views/admin/editor_settings/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t('rich_editor') %></h1>

<%= form_for(Spree::Editor::Config.instance, :url => admin_editor_settings_path) do |form| %>
  <fieldset id="preferences">
    <%= form.field_container :preferred_current_editor do %>
      <%= form.label(:preferred_current_editor, t('rich_editor_engine')) %>
      <%= form.select :preferred_current_editor, options_for_select(SpreeEditor::EditorEngines, Spree::Editor::Config[:current_editor])  %>
    <% end %>
    <%= form.field_container :preferred_enabled do %>
      <%= preference_field(form, :preferred_enabled, :type => :boolean) %>
      <%= form.label(:preferred_enabled, t(:enable_rich_editor)) %>
    <% end %>
    <%= form.field_container :preferred_ids do %>
      <%= form.label(:preferred_ids, t(:rich_editor_ids_description)+": ") + tag(:br) %>
      <%= preference_field(form, :preferred_ids, :type => :text) %>
    <% end %>
  </fieldset>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_editor_settings_url %>
  </p>
<% end %>

app/views/admin/editor_settings/show.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("rich_editor") %></h1>

<table>
  <tr>
    <td><%= t('enable_rich_editor') %>:</td>
    <td><%= Spree::Editor::Config[:enabled] ? t('yes') : t('no') %></td>
  </tr>
  <tr>
    <td><%= t('rich_editor_engine') %>:</td>
    <td><%= Spree::Editor::Config[:current_editor] %></td>
  </tr>
  <tr>
    <td><%= t('rich_editor_ids') %>:</td>
    <td><%= Spree::Editor::Config[:ids] %></td>
  </tr>
</table>

<p><%= link_to_with_icon 'edit', t("edit"), edit_admin_editor_settings_path %></p>

app/views/shared/_rich_editor_javascript.html.erb
<% is_enabled = Spree::Editor::Config[:enabled] %>
<% current_editor = Spree::Editor::Config[:current_editor] %>
<% ids = Spree::Editor::Config[:ids].split %>

<% if is_enabled and ids.any? %>
    <%= render :partial => "shared/editor_engines/#{Spree::Editor::Config[:current_editor].underscore}",
               :locals => { :ids => ids } %>
<% end %>

app/views/shared/editor_engines/_tiny_mce.html.erb
<script type="text/javascript" src="/javascripts/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="/javascripts/tinymce/jquery.tinymce.js"></script>

<script type="text/javascript">
    $(function() {
        var myConfig = { dompath: true };
        var ids = [<%= ids.map{|id| "'#{id}'"}.join(', ') %>]
        $.each(ids, function(index, id) {
            if ($('textarea#' + id).length) {
                tinyMCE.init({
                    mode : "exact",
                    elements : id,
                    theme : "advanced",
                    language : '<%= I18n.locale.to_s.downcase %>',
                    skin : "o2k7",
                    plugins : "safari,style,layer,table,advhr,advimage,inlinepopups,insertdatetime,preview,media,searchreplace,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

                    // Theme options
                    theme_advanced_buttons1 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,fullscreen,|,charmap,media,advhr,|,visualchars,nonbreaking,blockquote",
                    theme_advanced_buttons2 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,sub,sup,|,bullist,numlist,|,outdent,indent,blockquote,|,styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor",
                    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid",
                    theme_advanced_buttons4 : "",
                    theme_advanced_toolbar_location : "top",
                    theme_advanced_toolbar_align : "left",
                    theme_advanced_statusbar_location : "bottom",
                    theme_advanced_resizing : true,

                    // Example content CSS (should be your site CSS)
                    content_css : "css/example.css",

                    // Drop lists for link/image/media/template dialogs
                    template_external_list_url : "js/template_list.js",
                    external_link_list_url : "js/link_list.js",
                    external_image_list_url : "js/image_list.js",
                    media_external_list_url : "js/media_list.js",
                });
            }
        });
    });
</script>

app/views/shared/editor_engines/_wym_editor.html.erb
<script type="text/javascript" src="/javascripts/wymeditor/jquery.wymeditor.min.js"></script>

<script type="text/javascript">
  $(function() {
      var ids = [<%= ids.map{|id| "'textarea##{id}'"}.join(', ') %>]
      $(ids.join(', ')).wymeditor({ lang: '<%= I18n.locale.to_s.downcase %>', skin: 'compact' });
  });
</script>

app/views/shared/editor_engines/_yui_rich_editor.html.erb
<div class="editor-mask-container">
  <div class="editor-mask"></div>
  <div class="editor-mask-label"><%= t("editor.loading") %></div>
</div>

<!-- Skin CSS file -->

<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.2r1/build/editor/assets/skins/sam/editor.css"/>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.2r1/build/menu/assets/skins/sam/menu.css"/>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.2r1/build/button/assets/skins/sam/button.css"/>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.2r1/build/container/assets/skins/sam/container.css"/>
<%= stylesheet_link_tag 'editor' %>

<!-- Utility Dependencies -->
<script src="http://yui.yahooapis.com/2.8.2r1/build/yahoo-dom-event/yahoo-dom-event.js"></script>
<script src="http://yui.yahooapis.com/2.8.2r1/build/element/element-min.js"></script>
<!-- Needed for Menus, Buttons and Overlays used in the Toolbar -->
<script src="http://yui.yahooapis.com/2.8.2r1/build/container/container_core-min.js"></script>
<script src="http://yui.yahooapis.com/2.8.2r1/build/menu/menu-min.js"></script>
<script src="http://yui.yahooapis.com/2.8.2r1/build/button/button-min.js"></script>
<!-- Source file for Rich Text Editor-->
<script src="http://yui.yahooapis.com/2.8.2r1/build/editor/editor-min.js"></script>

<%= javascript_include_tag 'jquery.ocupload' %>

<script type="text/javascript">
    $(function() {
        var Dom = YAHOO.util.Dom,
  	        Event = YAHOO.util.Event;
        var myConfig = { dompath: true };
        var ids = [<%= ids.map{|id| "'#{id}'"}.join(', ') %>];
        $.each(ids, function(index, id) {
            if ($('textarea#' + id).length) {
                var state = 'off';
                var newEditor = window[id + '_editor'] = new YAHOO.widget.Editor(id, {
                    height: '350px',
                    width: 'auto',
                    animate: true,
                    handleSubmit: true,
                    toolbar: {
                        collapse: true,
                        titlebar: false,
                        draggable: false,
                        buttonType: 'advanced',
                        buttons: [
                            { group: 'fontstyle', label: '<%= t("editor.font_name_and_size") %>',
                                buttons: [
                                    { type: 'select', label: 'Arial', value: 'fontname', disabled: true,
                                        menu: [
                                            { text: 'Arial', checked: true },
                                            { text: 'Arial Black' },
                                            { text: 'Comic Sans MS' },
                                            { text: 'Courier New' },
                                            { text: 'Lucida Console' },
                                            { text: 'Tahoma' },
                                            { text: 'Times New Roman' },
                                            { text: 'Trebuchet MS' },
                                            { text: 'Verdana' }
                                        ]
                                    },
                                    { type: 'spin', label: '13', value: 'fontsize', range: [ 9, 75 ], disabled: true }
                                ]
                            },
                            { type: 'separator' },
                            { group: 'textstyle', label: '<%= t("editor.font_style") %> ',
                                buttons: [
                                    { type: 'push', label: '<%= t("editor.bold") %> CTRL + SHIFT + B', value: 'bold' },
                                    { type: 'push', label: '<%= t("editor.italic") %> CTRL + SHIFT + I', value: 'italic' },
                                    { type: 'push', label: '<%= t("editor.underline") %> CTRL + SHIFT + U', value: 'underline' },
                                    { type: 'separator' },
                                    { type: 'push', label: '<%= t("editor.subscript") %>', value: 'subscript', disabled: true },
                                    { type: 'push', label: '<%= t("editor.superscript") %>', value: 'superscript', disabled: true },
                                    { type: 'separator' },
                                    { type: 'color', label: '<%= t("editor.font_color") %>', value: 'forecolor', disabled: true },
                                    { type: 'color', label: '<%= t("editor.background_color") %>', value: 'backcolor', disabled: true },
                                    { type: 'separator' },
                                    { type: 'push', label: '<%= t("editor.remove_formatting") %>', value: 'removeformat', disabled: true },
                                    { type: 'push', label: '<%= t("editor.show_and_hide_hidden_elements") %>', value: 'hiddenelements' }
                                ]
                            },
                            { type: 'separator' },
                            { group: 'alignment', label: '<%= t("editor.alignment") %>',
                                buttons: [
                                    { type: 'push', label: '<%= t("editor.align_left") %> CTRL + SHIFT + [', value: 'justifyleft' },
                                    { type: 'push', label: '<%= t("editor.align_center") %> CTRL + SHIFT + |', value: 'justifycenter' },
                                    { type: 'push', label: '<%= t("editor.align_right") %> CTRL + SHIFT + ]', value: 'justifyright' },
                                    { type: 'push', label: '<%= t("editor.justify") %>', value: 'justifyfull' }
                                ]
                            },
                            { type: 'separator' },
                            { group: 'parastyle', label: '<%= t("editor.paragraph_style") %>',
                                buttons: [
                                    { type: 'select', label: '<%= t("editor.normal") %>', value: 'heading', disabled: true,
                                        menu: [
                                            { text: '<%= t("editor.normal") %>', value: 'none', checked: true },
                                            { text: '<%= t("editor.header") %> 1', value: 'h1' },
                                            { text: '<%= t("editor.header") %> 2', value: 'h2' },
                                            { text: '<%= t("editor.header") %> 3', value: 'h3' },
                                            { text: '<%= t("editor.header") %> 4', value: 'h4' },
                                            { text: '<%= t("editor.header") %> 5', value: 'h5' },
                                            { text: '<%= t("editor.header") %> 6', value: 'h6' }
                                        ]
                                    }
                                ]
                            },
                            { type: 'separator' },
                            { group: 'indentlist', label: '<%= t("editor.indenting_and_lists") %>',
                                buttons: [
                                    { type: 'push', label: '<%= t("editor.indent") %>', value: 'indent', disabled: true },
                                    { type: 'push', label: '<%= t("editor.outdent") %>', value: 'outdent', disabled: true },
                                    { type: 'push', label: '<%= t("editor.create_an_unordered_list") %>', value: 'insertunorderedlist' },
                                    { type: 'push', label: '<%= t("editor.create_an_ordered_list") %>', value: 'insertorderedlist' }
                                ]
                            },
                            { type: 'separator' },
                            { group: 'insertitem', label: '<%= t("editor.insert_item") %>',
                                buttons: [
                                    { type: 'push', label: '<%= t("editor.html_link") %> CTRL + SHIFT + L', value: 'createlink', disabled: true },
                                    { type: 'push', label: '<%= t("editor.insert_image") %>', value: 'insertimage' },
                                    { type: 'push', label: '<%= t("editor.edit_html_code") %>', value: 'editcode' }
                                ]
                            },
                            { type: 'separator' },
                            { group: 'uploaditem', label: '<%= t("editor.upload") %>',
                                buttons: [
                                    { type: 'push', label: '<%= t("editor.upload_image") %>', value: 'imageUpload' },
                                    { type: 'push', label: '<%= t("editor.upload_file") %>', value: 'fileUpload' }
                                ]
                            }

                        ]
                    }
                });

                newEditor.addListener('editorContentLoaded', function() {
                    $(".yui-toolbar-imageUpload").upload({
                        name: 'content_image[attachment]',
                        action: '/content_images',
                        enctype: 'multipart/form-data',
                        //params: {'content_image[viewable_type]': '<%# object.class.name %>', 'content_image[viewable_id]': '<%# object.id %>'},
                        autoSubmit: true,
                        onSubmit: function() {
                            $(".editor-mask-container").addClass("active");
                        },
                        onComplete: function(image_src) {
                            var img_html = "<img src='" + image_src + "'/>";
                            newEditor.execCommand('inserthtml', img_html);
                            $(".editor-mask-container").removeClass("active");
                        }
                    });

                    $(".yui-toolbar-fileUpload").upload({
                        name: 'content_file[attachment]',
                        action: '/content_files',
                        enctype: 'multipart/form-data',
                        //params: {'content_file[viewable_type]': '<%# object.class.name %>', 'content_file[viewable_id]': '<%# @object.id %>'},
                        autoSubmit: true,
                        onSubmit: function() {
                            $(".editor-mask-container").addClass("active");
                        },
                        onComplete: function(file_url_and_name) {
                            var file_url = file_url_and_name.split(",")[0];
                            var file_name_original = file_url_and_name.split(",")[1];
                            $(".editor-mask-container").removeClass("active");
                            var file_name = prompt('<%= t("editor.enter_file_name") %>', file_name_original);
                            var link_html = "<a href='" + file_url + "'/>" + file_name + "</a>";
                            newEditor.execCommand('inserthtml', link_html);
                        }
                    });
                });


                newEditor.on('toolbarLoaded', function() {
          	        this.toolbar.on('editcodeClick', function() {
          	            var ta = this.get('element'),
          	                iframe = this.get('iframe').get('element');

          	            if (state == 'on') {
          	                state = 'off';
          	                this.toolbar.set('disabled', false);
          	                this.setEditorHTML(ta.value);
          	                if (!this.browser.ie) {
          	                    this._setDesignMode('on');
          	                }

          	                Dom.removeClass(iframe, 'editor-hidden');
          	                Dom.addClass(ta, 'editor-hidden');
          	                this.show();
          	                this._focusWindow();
          	            } else {
          	                state = 'on';
          	                this.cleanHTML();
          	                Dom.addClass(iframe, 'editor-hidden');
          	                Dom.removeClass(ta, 'editor-hidden');
          	                this.toolbar.set('disabled', true);
          	                this.toolbar.getButtonByValue('editcode').set('disabled', false);
          	                this.toolbar.selectButton('editcode');
          	                this.dompath.innerHTML = 'Editing HTML Code';
          	                this.hide();
          	            }
          	            return false;
          	        }, this, true);

          	        this.on('cleanHTML', function(ev) {
          	            this.get('element').value = ev.html;
          	        }, this, true);

          	        this.on('afterRender', function() {
          	            var wrapper = this.get('editor_wrapper');
          	            wrapper.appendChild(this.get('element'));
          	            this.setStyle('width', '100%');
          	            this.setStyle('height', '100%');
          	            this.setStyle('visibility', '');
          	            this.setStyle('top', '');
          	            this.setStyle('left', '');
          	            this.setStyle('position', '');

          	            this.addClass('editor-hidden');
          	        }, this, true);
                }, newEditor, true);
                newEditor.render();
            }
        });
    });
</script>